# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  terraform-agent:
    docker:
      - image: hashicorp/terraform:1.0.0

jobs:
  plan:
    executor: terraform-agent
    parameters:
      working-dir:
        type: string
    steps:
      - checkout
      - run:
          name: terraform plan
          command: cd terraform/<< parameters.working-dir >> && terraform init && terraform plan
  apply:
    executor: terraform-agent
    parameters:
      working-dir:
        type: string
    steps:
      - checkout
      - run:
          name: terraform apply
          command: cd terraform/<< parameters.working-dir >> && terraform init && terraform apply -auto-approve

workflows:
  infrastructure:
    jobs:
      - plan:
          name: s3_plan
          context: nonprod
          working-dir: s3
      - approval-gate:
          name: s3_apply_approval
          type: approval
          requires:
            - s3_plan
      - apply:
          name: s3_apply
          context: nonprod
          working-dir: s3
          requires:
            - s3_apply_approval